### PR TITLE
Add paritionalloc to the comparison page

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by struct** [comment]
PartitionAlloc has some pointer obfuscation via 'encoded' freelist pointers. (cc @noncombatant)
 
I think a previous PR used `heavy_minus_mark` instead of `heavy_minus_sign`  and `heavy_plus_mark` instead of `heavy_check_mark`.

**Comment by jvoisin** [comment]
I think that we need to clarify what we mean by "pointer obfuscation": what did you have in mind for this particular item?

**Comment by struct** [comment]
I see 'pointer obfuscation' as a general way of saying "we have identified some key pointers where there is security value in encoding/obfuscating them" and whether that targets 1 or 10 pointer types it should still be green.

**Comment by jvoisin** [comment]
Then I'm a bit confused, because I can't see where in isoalloc some pointers are obfuscated :/

**Comment by struct** [comment]
These macros handle masking and unmasking zone and big-zone meta data https://github.com/struct/isoalloc/blob/master/include/iso_alloc_internal.h#L240-L257

**Comment by jvoisin** [comment]
Oh. This is a bit confusing, I thought it was a mask, for alignment purposes, and not a secret. Also my brains processed the `^` operators as an `|`, sigh.

**Comment by struct** [comment]
`Chunk Alignment Check` is always done in IsoAlloc on `free` https://github.com/struct/isoalloc/blob/master/src/iso_alloc.c#L1430

**Pull request merged**
