### PR TITLE
fix attempt #119

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by struct** [comment]
I tested this on MacOS 12.6 with `Apple clang version 14.0.0 (clang-1400.0.29.102)` and it seems to optimize away the call to `memcpy` in the `heap_overflow.c` test which means the `MEMCPY_SANITY` functionality is not tested. Did you observe the same thing?

**Comment by struct** [comment]
I still see the same behavior even with these changes. If you add some `LOG` statements to `_iso_alloc_memcpy()` you will see it is never called. Not sure why this is occurring just yet.

**Comment by devnexen** [comment]
we would need indeed to build as static library/build the tests with the c source each time (or reshift the whole library so if the code user wants to override memset/memcpy it would need to include the libc_hook implementation)

anyhow, so I get the hook to be called in those cases.

`build/heap_overflow
[LOG][49389](src/libc_hook.c:11 memcpy()) macOs here
[ABORTING][49389](src/iso_alloc_sanity.c:311 _iso_alloc_memcpy()) Detected an out of bounds write memcpy: dest=0x38591c7ec80 (32 bytes) src=0x1049e6c35 size=123`

**Comment by struct** [comment]
Ah you're right. That adds a lot of complexity just for these 2 modes. I also binary diffed the library with `D_FORTIFY_SOURCE=0` and `D_FORTIFY_SOURCE=1` (and 2) and no hardening is applied. So I don't see a reason to pursue this work just yet.

**Comment by struct** [comment]
Declining this based on the comment above. As the code stands today FORTIFY provides no value. I don't like not having FORTIFY enabled because future changes to the library could change that but the complexity required at the present doesn't seem worth it.

**Pull request closed without merging**
