### PR TITLE
Add a muls-based distribution in the CI

### PR DESCRIPTION
**Pull request by jvoisin**
I have no idea why the `thread_tests` are failing :/

### CODE REVIEW

**Comment by struct** [comment]
Do you have a stack trace for the thread_test failure?

**Comment by jvoisin** [comment]
Unfortunately not, since I was relying on the CI so far. I'll try to get a real stacktrace sometimes this week.

**Comment by jvoisin** [comment]
```C
~/isoalloc/build $ gdb ./thread_tests
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./thread_tests...
(gdb) b main
Breakpoint 1 at 0x16f6: file tests/thread_tests.c, line 110.
(gdb) r
Starting program: /home/jvoisin/isoalloc/build/thread_tests 

Breakpoint 1, main (argc=1, argv=0x7fffffffeb48) at tests/thread_tests.c:110
110	   if(argc != 2) {
(gdb) n
111	       times = 1;
(gdb) n
112	   } else {
(gdb) n
116	   run_test_threads();
(gdb) n
[New LWP 787]
[New LWP 788]
[New LWP 789]

Thread 3 "thread_tests" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 788]
0x00007ffff7f58e71 in populate_zone_cache (zone=0x0) at src/iso_alloc.c:1236
1236	       zone_cache[zone_cache_count].chunk_size = zone->chunk_size;
(gdb) bt
#0  0x00007ffff7f58e71 in populate_zone_cache (zone=0x0) at src/iso_alloc.c:1236
#1  iso_free_chunk_from_zone (zone=0xbe2b7ea3500, p=0x1c1893451000, permanent=false) at src/iso_alloc.c:1801
#2  0x00007ffff7f54f14 in _iso_free_internal_unlocked (p=0x1c1893451000, permanent=false, zone=0xbe2b7ea3500) at src/iso_alloc.c:1987
#3  0x00007ffff7f593d5 in _iso_free_size (p=0x1c1893451000, size=4096) at src/iso_alloc.c:1936
#4  0x00007ffff7f59962 in iso_realloc (p=0x1c1893451000, size=4096) at src/iso_alloc_interfaces.c:66
#5  0x0000555555555491 in allocate (_type=0x555555556004 <REALLOC>) at tests/thread_tests.c:59
#6  0x00007ffff7fba1f5 in ?? () from /lib/ld-musl-x86_64.so.1
#7  0x0000000000000000 in ?? ()
(gdb) info reg
rax            0x7ffff7f2d890      140737353275536
rbx            0x7ffff7f2d840      140737353275456
rcx            0x7ffff7f2d890      140737353275536
rdx            0x0                 0
rsi            0x0                 0
rdi            0x7ffff7f5ffc8      140737353482184
rbp            0x7ffff7f1d6c0      0x7ffff7f1d6c0
rsp            0x7ffff7f1d560      0x7ffff7f1d560
r8             0x0                 0
r9             0x0                 0
r10            0x0                 0
r11            0x0                 0
r12            0x7ffff7f2d840      140737353275456
r13            0x23000             143360
r14            0x7ffff7ffeb90      140737354132368
r15            0x7ffff7f2d860      140737353275488
rip            0x7ffff7f58e71      0x7ffff7f58e71 <iso_free_chunk_from_zone+2497>
eflags         0x10206             [ PF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
(gdb) 
```

**Comment by struct** [comment]
> 0x00007ffff7f58e71 in populate_zone_cache (zone=0x0)

Unless this is just an artifact of gdb being broken the `zone` pointer passed to `populate_zone_cache` should never be NULL. I can try to reproduce this in an Alpine Linux docker container.

**Comment by struct** [comment]
I tested this on Alpine Linux in a Docker container. I did run into a bug related to `thread_tests` where the array sizes and nested for loops were resulting in stack exhaustion. I've fixed that on master and the test worked on your branch. Can you rebase?

```
/code/isoalloc # uname -a
Linux 063039a28f43 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 Linux
/code/isoalloc # cat /etc/alpine-release 
3.15.4
```

**Pull request merged**
